name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Update Node.js version to meet Angular CLI requirements

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        run: |
          aws s3 sync ./dist/face-match-reborn/browser s3://api.theandrei.link
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: sa-east-1
